#include <iostream> [cite: 596]
#include <vector> [cite: 597]
using namespace std; [cite: 598]

class Graph { [cite: 599]
    int V; [cite: 600]
    vector<vector<int>> adj; [cite: 601]
public: [cite: 602]
    Graph(int n) { [cite: 603]
        V = n; [cite: 605]
        adj.resize(V); [cite: 606]
    } [cite: 604]

    void addEdge(int u, int v) { [cite: 607]
        adj[u].push_back(v); [cite: 609]
        adj [v].push_back(u); [cite: 610]
    } [cite: 608]

    // DFS function [cite: 611]
    void dfsUtil(int node, vector<bool> &visited) { [cite: 612]
        visited[node] = true; [cite: 613]
        cout << node << " "; [cite: 615]
        for (int nxt: adj [node]) { [cite: 616]
            if (!visited[nxt]) [cite: 617]
                dfsUtil(nxt, visited); [cite: 618]
        } [cite: 619]
    } [cite: 620]

    // DFS starter [cite: 621]
    void DFS(int start) { [cite: 622]
        vector<bool> visited(V, false); [cite: 623]
        dfsUtil(start, visited); [cite: 624]
    } [cite: 625]
}; [cite: 626]

int main() { [cite: 627]
    Graph g(5); [cite: 628]
    g.addEdge(0, 1); [cite: 629]
    g.addEdge(0, 2); [cite: 630]
    g.addEdge(1, 3); [cite: 631]
    g.addEdge(1, 4); [cite: 632]

    cout << "DFS Traversal: "; [cite: 633]
    g.DFS(0); [cite: 634]

    return 0; [cite: 636]
} [cite: 638]