#include <iostream> [cite: 466]
#include <string> [cite: 467]
#include <vector> [cite: 468]
using namespace std; [cite: 469]

class Person { [cite: 470]
public: [cite: 471]
    string fname, lname, phone; [cite: 472]
    Person* next; [cite: 473]
    Person(string f, string l, string p) { [cite: 474]
        fname = f; [cite: 475]
        lname = l; [cite: 476]
        phone = p; [cite: 477]
        next = NULL; [cite: 478]
    } [cite: 479]
}; [cite: 480]

class HashTable { [cite: 481]
    vector<Person*> table; [cite: 482]
    int size; [cite: 483]
public: [cite: 484]
    HashTable(int s = 10) { [cite: 485]
        size = s; [cite: 487]
        table.resize(size, NULL); [cite: 488]
    } [cite: 486]

    // Simple hash function -> sum of ASCII characters of first name 
    int hashFunc(string name) { [cite: 490]
        int sum = 0; [cite: 491]
        for (char c : name) sum += c; [cite: 492, 493]
        return sum % size; [cite: 494]
    } [cite: 495]

    // Insert record [cite: 496]
    void insertRecord (string f, string l, string p) { [cite: 497]
        int index = hashFunc(f); [cite: 498]
        Person* newNode = new Person(f, l, p); [cite: 499]
        // Insert at head of linked list (chaining) [cite: 500]
        newNode->next = table[index]; [cite: 501]
        table[index] = newNode; [cite: 502]
    } [cite: 503]

    // Search record [cite: 504]
    Person* searchRecord (string f) { [cite: 505]
        int index = hashFunc(f); [cite: 506]
        Person* temp = table[index]; [cite: 507]
        while (temp) { [cite: 508]
            if (temp->fname == f) [cite: 509]
                return temp; [cite: 510]
            temp = temp->next; [cite: 511]
        } [cite: 512]
        return NULL; [cite: 514]
    } [cite: 513]

    // Delete record [cite: 515]
    void deleteRecord (string f) { [cite: 516]
        int index = hashFunc(f); [cite: 517]
        Person* temp = table[index]; [cite: 518]
        Person* prev = NULL; [cite: 519]
        while (temp) { [cite: 520]
            if (temp->fname == f) { [cite: 521]
                if (prev) prev->next = temp->next; [cite: 522]
                else table[index] = temp->next; [cite: 523]
                delete temp; [cite: 524]
                cout << "Record deleted.\n"; [cite: 525]
                return; [cite: 527]
            } [cite: 526]
            prev = temp; [cite: 528]
            temp = temp->next; [cite: 529]
        } [cite: 530]
        cout << "Record not found.\n"; [cite: 531]
    } [cite: 532]

    // Display Hash Table [cite: 533]
    void display() { [cite: 534]
        for (int i = 0; i < size; i++) { [cite: 535]
            cout << i << "->"; [cite: 536]
            Person* temp = table[i]; [cite: 537]
            while (temp) { [cite: 538]
                cout << "[" << temp->fname << " " << temp->lname [cite: 539]
                     << " : " << temp->phone << "] -> "; [cite: 540, 541, 542, 543, 544]
                temp = temp->next; [cite: 545]
            } [cite: 546]
            cout << "NULL\n"; [cite: 547]
        } [cite: 548]
    } [cite: 549]
}; [cite: 550]

int main() { [cite: 551]
    HashTable ht; [cite: 552]
    ht.insertRecord("Aman", [cite: 553]
                    "Sharma", "9999999999"); [cite: 554]
    ht.insertRecord ("Riya", [cite: 555]
                    "Verma", "8888888888"); [cite: 556]
    ht.insertRecord("Rohit", [cite: 557]
                    "Kumar", "7777777777"); [cite: 558]

    cout << "\nHash Table:\n"; [cite: 559]
    ht.display(); [cite: 560]

    cout << "\nSearching for 'Riya'...\n"; [cite: 561]
    Person* p = ht.searchRecord ("Riya"); [cite: 562]
    if (p) cout << p->fname << " " << p->lname << ": " << p->phone << endl; [cite: 563]
    else cout << "Not found\n"; [cite: 564]

    cout << "\nDeleting 'Aman'...\n"; [cite: 565]
    ht.deleteRecord("Aman"); [cite: 567]

    cout << "\nAfter Deletion:\n"; [cite: 568]
    ht.display(); [cite: 569]

    return 0; [cite: 570]
} [cite: 566]